# Generated by Django 6.0.4 on 2026-05-04 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=120, unique=True)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('national_id', models.CharField(db_column='National_Id', max_length=20, unique=True)),
                ('phone_number', models.CharField(db_column='Phone_Number', max_length=20, unique=True)),
                ('email', models.EmailField(db_column='Email', max_length=254, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=255)),
                ('user_type', models.CharField(choices=[('citizin', 'Citizin'), ('employee', 'Employee')], db_column='User_Type', max_length=20)),
                ('role', models.CharField(blank=True, choices=[('technical', 'Technical'), ('operator', 'Operator'), ('admin', 'Admin'), ('supervisior', 'Supervisior')], db_column='Role', max_length=20, null=True)),
                ('region', models.CharField(blank=True, db_column='Region', max_length=120, null=True)),
                ('birthdate', models.DateField(blank=True, db_column='Birthdate', null=True)),
                ('username', models.CharField(blank=True, db_column='Username', max_length=150, null=True, unique=True)),
                ('department', models.ForeignKey(blank=True, db_column='Department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.department')),
            ],
            options={
                'db_table': 'Users',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('user_type', 'employee'), _negated=True), models.Q(('role__isnull', False), models.Q(('role', ''), _negated=True), ('department__isnull', False), ('region__isnull', False), models.Q(('region', ''), _negated=True)), _connector='OR'), name='employee_required_fields'), models.CheckConstraint(condition=models.Q(models.Q(('user_type', 'citizin'), _negated=True), models.Q(('birthdate__isnull', False), ('username__isnull', False), models.Q(('username', ''), _negated=True)), _connector='OR'), name='citizin_required_fields')],
            },
        ),
    ]
