# Generated by Django 6.0.4 on 2026-05-04 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(db_column='National_Id', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(db_column='Phone_Number', max_length=11, unique=True),
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_column='Email', max_length=254)),
                ('otp_code', models.CharField(db_column='OTP_Code', max_length=6)),
                ('is_verified', models.BooleanField(db_column='Is_Verified', default=False)),
                ('is_used', models.BooleanField(db_column='Is_Used', default=False)),
                ('expires_at', models.DateTimeField(db_column='Expires_At')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_At')),
                ('user', models.ForeignKey(db_column='User_Id', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_otps', to='users.user')),
            ],
            options={
                'db_table': 'Password_Reset_OTP',
                'indexes': [models.Index(fields=['email', 'otp_code'], name='Password_Re_Email_a18d24_idx'), models.Index(fields=['email', 'is_verified', 'is_used'], name='Password_Re_Email_c13dcd_idx')],
            },
        ),
    ]
