# Generated by Django 6.0.4 on 2026-05-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_national_id_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='logo',
            field=models.FileField(blank=True, db_column='Logo', null=True, upload_to='departments/logos/'),
        ),
    ]
