# Generated by Django 6.0.4 on 2026-05-04 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_department_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(db_column='Description')),
                ('latlatitude', models.DecimalField(db_column='Latlatitude', decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(db_column='Longitude', decimal_places=7, max_digits=10)),
                ('location_name', models.CharField(db_column='Location_Name', max_length=255)),
                ('status', models.CharField(choices=[('New', 'New'), ('Assigned', 'Assigned'), ('In_Progress', 'In_Progress'), ('Review', 'Review'), ('Forworded', 'Forworded'), ('Finished', 'Finished')], db_column='Status', default='New', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], db_column='Priority', default='Medium', max_length=10)),
                ('image_before_analysis', models.FileField(blank=True, db_column='Image_Before_Analysis', null=True, upload_to='incidence/before/')),
                ('image_after_analysis', models.FileField(blank=True, db_column='Image_After_Analysis', null=True, upload_to='incidence/after/')),
                ('ai_analysis_label_before', models.CharField(blank=True, db_column='Ai_Analysis_Label_Before', max_length=255, null=True)),
                ('ai_analysis_label_after', models.CharField(blank=True, db_column='Ai_Analysis_Label_After', max_length=255, null=True)),
                ('assigned_employee', models.ForeignKey(blank=True, db_column='Assigned_Employee_Id', limit_choices_to={'user_type': 'employee'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidences', to='users.user')),
                ('citizin', models.ForeignKey(db_column='Citizin_Id', limit_choices_to={'user_type': 'citizin'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_incidences', to='users.user')),
                ('department', models.ForeignKey(blank=True, db_column='Department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidences', to='users.department')),
            ],
            options={
                'db_table': 'Incidence',
            },
        ),
    ]
