# Generated by Django 6.0.4 on 2026-05-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_incidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidence',
            name='image_before_analysis',
            field=models.FileField(db_column='Image_Before_Analysis', null=True, upload_to='incidence/before/'),
        ),
        migrations.AlterField(
            model_name='incidence',
            name='priority',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], db_column='Priority', max_length=10, null=True),
        ),
    ]
