# Generated by Django 6.0.4 on 2026-05-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_incidence_image_before_analysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence',
            name='location_confirmation',
            field=models.BooleanField(db_column='Location_Confirmation', default=False),
        ),
    ]
