# Generated by Django 6.0.4 on 2026-05-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_incidence_location_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence',
            name='what_was_done',
            field=models.TextField(blank=True, db_column='What_was_done', null=True),
        ),
    ]
