# Generated by Django 6.0.4 on 2026-05-05 12:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_incidence_what_was_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence',
            name='dashboard_date',
            field=models.DateField(db_column='Dashboard_Date', db_index=True, default=django.utils.timezone.localdate),
        ),
    ]
