# Generated by Django 6.0.4 on 2026-05-05 13:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_incidence_dashboard_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence',
            name='created_at',
            field=models.DateTimeField(db_column='Created_At', db_index=True, default=django.utils.timezone.now),
        ),
    ]
