# Generated by Django 6.0.4 on 2026-05-05 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_incidence_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(db_column='Location_Name', max_length=255)),
                ('latlatitude', models.DecimalField(db_column='Latlatitude', decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(db_column='Longitude', decimal_places=7, max_digits=10)),
                ('priority', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], db_column='Priority', max_length=10, null=True)),
                ('department_name', models.CharField(db_column='Department_Name', max_length=120)),
                ('employee_name', models.CharField(db_column='Employee_Name', max_length=255)),
                ('employee_email', models.EmailField(db_column='Employee_Email', max_length=254)),
                ('is_read', models.BooleanField(db_column='Is_Read', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_At', db_index=True)),
                ('incidence', models.ForeignKey(db_column='Incidence_Id', on_delete=django.db.models.deletion.CASCADE, related_name='operator_notifications', to='users.incidence')),
                ('operator', models.ForeignKey(db_column='Operator_Id', limit_choices_to={'role': 'operator', 'user_type': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_operator_notifications', to='users.user')),
                ('sender_employee', models.ForeignKey(db_column='Sender_Employee_Id', limit_choices_to={'user_type': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_operator_notifications', to='users.user')),
            ],
            options={
                'db_table': 'Operator_Notification',
                'indexes': [models.Index(fields=['operator', 'is_read', 'created_at'], name='Operator_No_Operato_9df017_idx'), models.Index(fields=['incidence', 'created_at'], name='Operator_No_Inciden_0478fb_idx')],
            },
        ),
    ]
