# Generated by Django 6.0.4 on 2026-05-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_column='Completed_At', null=True),
        ),
    ]
