# Generated by Django 6.0 on 2026-04-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="citizenprofile",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
