# Generated by Django 6.0 on 2025-12-20 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="id",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "citizen"), (2, "employee"), (3, "admin")],
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="users",
                to="accounts.role",
            ),
        ),
    ]
