# Generated by Django 5.2.11 on 2026-02-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_incident_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
