# Generated by Django 6.0 on 2026-02-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0004_incident_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="priority",
            field=models.CharField(
                choices=[("low", "منخفضة"), ("medium", "متوسطة"), ("high", "عالية")],
                default="medium",
                max_length=10,
            ),
        ),
    ]
