# Generated by Django 6.0 on 2026-02-14 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0005_alter_incident_priority"),
        ("incidents", "0005_incident_resolved_at_alter_incident_priority"),
    ]

    operations = []
